In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1], [2], [3]])
print(a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
import numpy as np  
arr = np.arange(12).reshape(3, 4)
print(arr[1:3, 1:3])

[[ 5  6]
 [ 9 10]]


In [3]:
import numpy as np
arr = np.array([-2, -1, 0, 1, 2])
arr[arr<0]=0
print(arr)

[0 0 0 1 2]


In [4]:
import numpy as np
matrix = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(np.nanmean(matrix,axis=1))

[2.  4.5]


In [5]:
import numpy as np
data = np.array([10, 20, 30, 40])
idx = np.array([True, False, True, False])
print(data[idx])

[10 30]


In [6]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df=pd.DataFrame(data,index=[100,101,102])
print(df)




        Name  Age
100    Alice   25
101      Bob   30
102  Charlie   35


In [7]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1, 2, np.nan], 'B': [np.nan, 5, 6]})
df['B']=df['B'].fillna(df['B'].mean())
print(df)

     A    B
0  1.0  5.5
1  2.0  5.0
2  NaN  6.0


In [8]:
import pandas as pd
df = pd.DataFrame({
       'Region': ['North', 'South', 'North', 'South'],
       'Sales': [100, 200, 150, 250],
       'Profit': [20, 30, 25, 40]
   })
grouped = df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'mean'}).reset_index()  
print(grouped)

  Region  Sales  Profit
0  North    250    22.5
1  South    450    35.0


In [11]:
import pandas as pd
orders = pd.DataFrame({'order_id': [1, 2], 'cust_id': [101, 102]})
customers = pd.DataFrame({'cust_id': [101, 103], 'name': ['Alice', 'Bob']})
merged=pd.merge(orders,customers,on='cust_id',how='left')
print(merged)


   order_id  cust_id   name
0         1      101  Alice
1         2      102    NaN


In [12]:
import pandas as pd
df = pd.DataFrame({
        'Date': ['2023-01-05', '2023-01-15', '2023-02-10'],
        'Value': [10, 20, 30]
    })
df['Date']=pd.to_datetime(df['Date'])
df['Month']=df['Date'].dt.month
print(df)
print(df.groupby('Month')['Value'].sum())


        Date  Value  Month
0 2023-01-05     10      1
1 2023-01-15     20      1
2 2023-02-10     30      2
Month
1    30
2    30
Name: Value, dtype: int64
